title: Innovation Lab
description: Innovation Lab, Universidad Galileo.

url: "https://InnovationLabUGProjects.github.io/"
baseurl: ""

markdown: kramdown
highlighter: rouge

navigation:
 - title: Home
   url: /index.html
 - title: Staff
   url: /staff.html
 - title: Proyects
   url: /projects.html
 - title: Presentations
   url: /presentations.html
 - title: Workshops
   url: /workshops.html

social:
   github: InnovationLabUG
